export const GENERATE_RANDOM_WORD = 'GENERATE_RANDOM_WORD';
export const CHECK_GUESS_WORD = 'CHECK_GUESS_WORD';
export const SAVE_DATA_SCORE_PLAYER = 'SAVE_DATA_SCORE_PLAYER';
export const RESET_LIFE_PLAYER = 'RESET_LIFE_PLAYER';
